library(data.table)
library(dplyr)
#setwd("./getDataW3/UCI HAR Dataset")
features<-read.table("features.txt",stringsAsFactors = F)
X_train<-fread("train/X_train.txt",col.names = features$V2)
y_train<-fread("train/y_train.txt")
subject_train<-fread("train/subject_train.txt")
dfTrain<-cbind(subject=subject_train,activity=y_train,X_train)

X_test<-fread("test/X_test.txt",col.names = features$V2)
y_test<-fread("test/y_test.txt")
subject_test<-fread("test/subject_test.txt")
dfTest<-cbind(subject=subject_test,activity=y_test,X_test)
tidy_data<-rbind(dfTrain,dfTest)
tidy_data2<-select(tidy_data,grep('V1|mean|std',names(tidy_data)))
activity_labels<-read.table("activity_labels.txt",stringsAsFactors = F)
tidy_data3<-merge(tidy_data2,activity_labels,by.x = "activity.V1",by.y = "V1")
tidy_data4<-rename(tidy_data3,ActivityName=V2,ActivityCode=activity.V1,Subject=subject.V1)

tidy_data5<-tidy_data4 %>% group_by(ActivityName,ActivityCode,Subject)%>% summarize_each(funs(mean))
write.table(tidy_data5,file = "tidy_data.txt",row.name=FALSE)
